-- Create daily_quotes table for 365 motivational quotes
CREATE TABLE public.daily_quotes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  day_of_year INTEGER NOT NULL UNIQUE CHECK (day_of_year >= 1 AND day_of_year <= 366),
  quote TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.daily_quotes ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read quotes (public data)
CREATE POLICY "Daily quotes are publicly readable" 
ON public.daily_quotes 
FOR SELECT 
USING (true);

-- Create index for quick lookup by day
CREATE INDEX idx_daily_quotes_day_of_year ON public.daily_quotes(day_of_year);

-- Insert all 365 quotes
INSERT INTO public.daily_quotes (day_of_year, quote) VALUES
(1, 'Você tem poder sobre sua mente — não sobre eventos.'),
(2, 'A vida é o que seus pensamentos fazem dela.'),
(3, 'Comece onde estiver. Use o que tiver. Faça o que puder.'),
(4, 'A jornada de mil milhas começa com um passo.'),
(5, 'Faça o melhor hoje; o amanhã se resolve depois.'),
(6, 'Disciplina é liberdade.'),
(7, 'Não espere por motivação — crie hábito.'),
(8, 'Foco é a moeda do resultado.'),
(9, 'Você falha apenas quando desiste.'),
(10, 'A clareza precede a escolha.'),
(11, 'O que importa é o próximo passo.'),
(12, 'Menos distração, mais execução.'),
(13, 'A dor do esforço é temporária; o orgulho é para sempre.'),
(14, 'Planejar é respeitar seu futuro.'),
(15, 'A coragem aparece em pequenos atos.'),
(16, 'Faça hoje o que seu eu futuro agradecerá.'),
(17, 'Progresso é somado por ações diárias.'),
(18, 'Quem governa a si mesmo, governa muito.'),
(19, 'Aceite o que não pode mudar; mude o que pode.'),
(20, 'A intenção organiza o esforço.'),
(21, 'Pequenos hábitos, grandes destinos.'),
(22, 'O tempo é um recurso implacável.'),
(23, 'Priorize o que gera consequência.'),
(24, 'Ação consistente vence talento ocasional.'),
(25, 'Seja melhor que ontem.'),
(26, 'O controle interno é sua vantagem.'),
(27, 'A escolha de hoje define sua história.'),
(28, 'Menos perfeição, mais progresso.'),
(29, 'Resiliência é trabalhar quando dói.'),
(30, 'Responsabilidade transforma desculpas em resultados.'),
(31, 'Faça primeiro o que mais importa.'),
(32, 'Saber o porquê sustenta o como.'),
(33, 'Quem planta rotina, colhe liberdade.'),
(34, 'A disciplina protege seu tempo.'),
(35, 'O hábito certo elimina debate.'),
(36, 'Persistir é criar caminho.'),
(37, 'Intenção sem ação é desejo.'),
(38, 'Não adie o essencial.'),
(39, 'A clareza reduz a ansiedade.'),
(40, 'Ação imperfeita vale mais que espera perfeita.'),
(41, 'A consistência constrói reputação.'),
(42, 'O propósito organiza sacrifício.'),
(43, 'Vença a resistência do primeiro minuto.'),
(44, 'Seja dono de suas prioridades.'),
(45, 'Sucesso é soma de hábitos.'),
(46, 'A mente treinada escolhe melhor.'),
(47, 'Decida cedo; ajuste depois.'),
(48, 'Planejamento claro reduz erros.'),
(49, 'Regra do 1%: melhore um pouco todo dia.'),
(50, 'A disciplina é construída em repetições.'),
(51, 'O maior investimento é em si mesmo.'),
(52, 'Quanto mais simples, mais executável.'),
(53, 'Não confunda atividade com progresso.'),
(54, 'O hábito de hoje define o amanhã.'),
(55, 'A responsabilidade antecede a liberdade.'),
(56, 'Controle a atenção; controle a vida.'),
(57, 'O sucesso começa com uma rotina.'),
(58, 'Pare de reagir, comece a escolher.'),
(59, 'A força está na constância.'),
(60, 'A coragem começa com um sim.'),
(61, 'Realize mais com menos distração.'),
(62, 'Autoconhecimento é vantagem competitiva.'),
(63, 'Menos consumo, mais criação.'),
(64, 'A clareza elimina o desnecessário.'),
(65, 'Faça hoje o que vai moldar sua identidade.'),
(66, 'O que você pratica se torna você.'),
(67, 'Planeje menos sonhos, crie mais sistema.'),
(68, 'Ajudar-se é responsabilidade primeira.'),
(69, 'Progresso pequeno, efeito duradouro.'),
(70, 'Persistência é estratégia de longo prazo.'),
(71, 'O controle começa na atenção.'),
(72, 'Concentre esforço onde há retorno.'),
(73, 'A vida recompensa consistência.'),
(74, 'Quem organiza vence o acaso.'),
(75, 'Transforme intenção em rituais.'),
(76, 'O hábito certo reduz fadiga decisória.'),
(77, 'Comprometa-se com seus prazos.'),
(78, 'O silêncio interno melhora decisões.'),
(79, 'Faça menos, faça melhor.'),
(80, 'A coragem é prática, não sentimento.'),
(81, 'Aprender é ação contínua.'),
(82, 'O trabalho consistente constrói confiança.'),
(83, 'Pequenos ganhos somam grandes vitórias.'),
(84, 'A vida exige escolhas; escolha bem.'),
(85, 'Sem sacrifício não há transformação.'),
(86, 'A gratificação atrasada gera liberdade.'),
(87, 'O progresso exige feedback honesto.'),
(88, 'Intenção sem limite vira vagueza.'),
(89, 'Seja o arquiteto das suas rotinas.'),
(90, 'Repetição constrói competência.'),
(91, 'A disciplina é um ato de respeito.'),
(92, 'Defina metas; defina ações.'),
(93, 'O autocontrole multiplica resultados.'),
(94, 'Mude hábitos, mude trajetória.'),
(95, 'Pratique o que planeja.'),
(96, 'A decisão é maior que o desejo.'),
(97, 'A vida responde a quem age.'),
(98, 'Assuma o leme da sua rotina.'),
(99, 'A clareza é um ato de gentileza consigo.'),
(100, 'O tempo bem gasto retorna em progresso.'),
(101, 'O medo diminui quando você age.'),
(102, 'Repetir o certo cria liberdade.'),
(103, 'Cultive a paciência ativa.'),
(104, 'Escolhas pequenas, impacto grande.'),
(105, 'Decida o que é inegociável.'),
(106, 'A vitória começa com o hábito.'),
(107, 'Treine sua atenção como músculo.'),
(108, 'Faça uma coisa difícil por dia.'),
(109, 'A disciplina constrói identidade.'),
(110, 'A simplicidade facilita o início.'),
(111, 'A rotina protege contra o imprevisível.'),
(112, 'Seja persistente até ver resultado.'),
(113, 'A clareza reduz desperdício de energia.'),
(114, 'Quanto mais cedo, mais vantagem.'),
(115, 'Comprometa-se com o processo.'),
(116, 'Ações conscientes geram confiança.'),
(117, 'Um passo consistente vale dez desculpas.'),
(118, 'Aja antes de se sentir pronto.'),
(119, 'A rotina é o combustível do progresso.'),
(120, 'Trabalhe em silêncio; deixe o resultado falar.'),
(121, 'Seja maior que sua resistência.'),
(122, 'Método vence talento ocasional.'),
(123, 'Organize hoje para ganhar amanhã.'),
(124, 'O autocontrole é um superpoder escondido.'),
(125, 'Transforme esforço em hábito útil.'),
(126, 'A ação pequena é ação concreta.'),
(127, 'Pense menos; faça mais.'),
(128, 'Planejar é mudar o possível.'),
(129, 'A prontidão vem do preparo.'),
(130, 'Persistir é a arte de continuar.'),
(131, 'A vida premia os que se organizam.'),
(132, 'O primeiro passo é sempre decisivo.'),
(133, 'Repetição cria confiança implícita.'),
(134, 'Disciplina cria fôlego para o longo prazo.'),
(135, 'Priorize estrategicamente seu tempo.'),
(136, 'A clareza é investimento diário.'),
(137, 'Faça do pequeno um ritual poderoso.'),
(138, 'Consistência é sinal de maturidade.'),
(139, 'Quem paga o preço hoje colhe depois.'),
(140, 'Mais execução, menos justificativa.'),
(141, 'A mente calma age com eficácia.'),
(142, 'Vença o barulho, preserve a meta.'),
(143, 'A rotina inteligente libera energia criativa.'),
(144, 'Cresça nos detalhes do dia a dia.'),
(145, 'O hábito certo economiza força de vontade.'),
(146, 'Faça da disciplina sua vantagem invisível.'),
(147, 'Simplifique para acelerar.'),
(148, 'A força do amanhã nasce hoje.'),
(149, 'Escolha o que edifica a longo prazo.'),
(150, 'O esforço repetido constrói excelência.'),
(151, 'A ação inteligente é sua melhor estratégia.'),
(152, 'Progrida um pouco mais do que ontem.'),
(153, 'Pequenos hábitos vencem grandes medos.'),
(154, 'A mente disciplinada tem liberdade.'),
(155, 'Faça do possível a sua base.'),
(156, 'O foco transforma intenção em realidade.'),
(157, 'Trabalhe primeiro no que mais importa.'),
(158, 'A persistência reduz a incerteza.'),
(159, 'Crie rituais que sustentem objetivos.'),
(160, 'A ação diária constrói domínio.'),
(161, 'Planejar pouco é confiar na sorte.'),
(162, 'O progresso é a soma das decisões corretas.'),
(163, 'Priorize: energia é limitada.'),
(164, 'Faça do princípio do 80/20 sua ferramenta.'),
(165, 'Decida e aja; ajuste no caminho.'),
(166, 'A disciplina é prática de longo prazo.'),
(167, 'A estabilidade vem do hábito.'),
(168, 'Comprometa-se com melhorias constantes.'),
(169, 'O resultado é fruto do processo.'),
(170, 'Melhore o sistema, não apenas a vontade.'),
(171, 'A ação cria perspectiva.'),
(172, 'Seja obsessivo com a execução.'),
(173, 'Uma escolha molda sua identidade.'),
(174, 'Persistir transforma intenção em rotina.'),
(175, 'Trabalhe com propósito, não só com pressa.'),
(176, 'O esforço deliberado gera maestria.'),
(177, 'A coerência gera credibilidade.'),
(178, 'A vida melhora com responsabilidade.'),
(179, 'Escolha progressos reais, não ilusões.'),
(180, 'Pratique o que ainda é difícil.'),
(181, 'Transforme seus piores minutos em treino.'),
(182, 'O hábito certo é um multiplicador.'),
(183, 'Decida hoje pelo seu eu de um ano.'),
(184, 'A prontidão vem de repetição diária.'),
(185, 'A consistência elimina dúvida.'),
(186, 'Trabalhe em silêncio; alcance alto.'),
(187, 'Pequenas vitórias mantêm o ritmo.'),
(188, 'A disciplina é amor pelo futuro.'),
(189, 'Construa seu dia com intenção.'),
(190, 'A rotina certa é um cofre de resultados.'),
(191, 'A vida recompensa quem age com critério.'),
(192, 'A clareza é antídoto contra a procrastinação.'),
(193, 'Decisões simples bem tomadas impactam muito.'),
(194, 'Pratique mais do que planeja.'),
(195, 'Resultados nascem de hábitos diários.'),
(196, 'Transforme disciplina em identidade.'),
(197, 'A consistência é a linguagem do sucesso.'),
(198, 'A rotina é o mapa da sua vida.'),
(199, 'Aja hoje pelo que quer colher amanhã.'),
(200, 'O controle da atenção é domínio pessoal.'),
(201, 'O esforço consciente supera o talento sem prática.'),
(202, 'Defina limites; eles criam liberdade.'),
(203, 'Descomplique: comece pequeno.'),
(204, 'A coragem é um hábito treinável.'),
(205, 'Menos teoria, mais execução.'),
(206, 'Rotina inteligente gera alavanca.'),
(207, 'A ação focada aumenta retorno.'),
(208, 'A disciplina vence a inspiração volátil.'),
(209, 'Seja consistente nos fundamentos.'),
(210, 'Faça hoje o que seu futuro agradecerá.'),
(211, 'A clareza diminui o ruído decisório.'),
(212, 'Pequenos hábitos sustentam grandes metas.'),
(213, 'A rotina é o esqueleto da produtividade.'),
(214, 'Quebre metas em tarefas diárias.'),
(215, 'Ação intencional reduz arrependimento.'),
(216, 'Trabalhe com foco estratégico.'),
(217, 'Treine a paciência orientada.'),
(218, 'O hábito certo torna escolhas fáceis.'),
(219, 'A disciplina é prática de amor próprio.'),
(220, 'A consistência constrói reputação e competência.'),
(221, 'Objetivos grandes pedem rotinas pequenas.'),
(222, 'A sua disciplina é seu patrimônio.'),
(223, 'Menos distrações, mais execução.'),
(224, 'A repetição é aliada do domínio.'),
(225, 'Planeje o futuro; execute o presente.'),
(226, 'Assuma 100% da sua agenda.'),
(227, 'A rotina certa economiza vontade.'),
(228, 'Concentre-se no essencial, descarte o resto.'),
(229, 'Pequenos avanços são vitórias reais.'),
(230, 'A consistência é o cimento do progresso.'),
(231, 'A disciplina não é punitiva; é libertadora.'),
(232, 'Trabalhe hoje para não lamentar amanhã.'),
(233, 'A clareza de propósito alinha escolhas.'),
(234, 'Construa sistemas, não apenas metas.'),
(235, 'A ação te ensina o caminho.'),
(236, 'Eficiência nasce da rotina estruturada.'),
(237, 'Repetir o certo é um ato de sabedoria.'),
(238, 'Disciplina cria margem para criatividade.'),
(239, 'Faça menos, faça melhor, faça sempre.'),
(240, 'A consistência vence a intensidade ocasional.'),
(241, 'A rotina é a arquitetura do sucesso.'),
(242, 'Seja firme nas pequenas decisões.'),
(243, 'Progresso exige disciplina e paciência.'),
(244, 'Aja como se o futuro dependesse disso — porque depende.'),
(245, 'Repetição gera confiança interna.'),
(246, 'A clareza é a base da eficácia.'),
(247, 'Planejamento e execução são gêmeos.'),
(248, 'Disciplina é escolher longo prazo.'),
(249, 'Um hábito hoje, uma vitória amanhã.'),
(250, 'Aja mais. Pense melhor. Repita.'),
(251, 'A rotina é o espaço onde o sucesso acontece.'),
(252, 'A consistência é prova de caráter.'),
(253, 'Não subestime pequenas melhorias.'),
(254, 'A disciplina é seu investimento diário.'),
(255, 'Crie rituais que te elevem.'),
(256, 'A clareza reduz medo e inércia.'),
(257, 'Comprometa-se com progresso diário.'),
(258, 'Pequenos hábitos, efeitos monumentais.'),
(259, 'A rotina transforma intenção em resultado.'),
(260, 'Seja irreversível em suas decisões cruciais.'),
(261, 'Disciplina é fazer o que importa, sempre.'),
(262, 'O trabalho constante vence o talento esquivo.'),
(263, 'A clareza dá velocidade ao esforço.'),
(264, 'Planeje hábitos, não só metas.'),
(265, 'A rotina inteligente preserva energia mental.'),
(266, 'A persistência é um diferencial competitivo.'),
(267, 'Mantenha o foco; descarte ruídos.'),
(268, 'A disciplina cria tranquilidade interior.'),
(269, 'Pequenos hábitos criam uma vida consistente.'),
(270, 'Faça o essencial com excelência.'),
(271, 'Priorize aquilo que alimenta o futuro.'),
(272, 'Ação bem escolhida vale mais que múltiplas ações.'),
(273, 'A rotina faz a diferença invisível.'),
(274, 'A persistência quebra resistência.'),
(275, 'Transforme intenção em técnica.'),
(276, 'A consistência é a linguagem da maestria.'),
(277, 'Crie sistemas para suportar ambição.'),
(278, 'Disciplina é amor pelo resultado.'),
(279, 'A prática diária cria competência duradoura.'),
(280, 'Foque no processo, não só na meta.'),
(281, 'Uma rotina firme é uma vida protegida.'),
(282, 'Persistir é honrar o plano.'),
(283, 'A clareza nasce de perguntas assertivas.'),
(284, 'Aja como se cada dia importasse — porque importa.'),
(285, 'A disciplina é reflexo de prioridades.'),
(286, 'Pequenas ações bem feitas criam reputação.'),
(287, 'Organize o seu dia como um investidor organiza carteira.'),
(288, 'A repetição transforma habilidade em reflexo.'),
(289, 'Planejar é tornar provável o sucesso.'),
(290, 'A consistência é um compromisso silencioso.'),
(291, 'A disciplina reduz arrependimentos futuros.'),
(292, 'Tenha método; o resto será consequência.'),
(293, 'Comprometa-se com o progresso anônimo.'),
(294, 'O sucesso repete rotinas discretas.'),
(295, 'A clareza na ação evita desperdício.'),
(296, 'A disciplina constrói liberdade financeira interna.'),
(297, 'Ritualize o importante.'),
(298, 'A consistência é o único atalho legítimo.'),
(299, 'A disciplina transforma intenção em legado.'),
(300, 'Faça do dia a unidade do seu avanço.'),
(301, 'A excelência nasce de hábitos modestos.'),
(302, 'Proteja sua atenção como protegeria seu tempo.'),
(303, 'Faça hoje o que seu sonho exige amanhã.'),
(304, 'Consistência é a língua do progresso real.'),
(305, 'A disciplina dá poder às suas escolhas.'),
(306, 'Trabalhe sistematicamente, conquiste exponencialmente.'),
(307, 'Pequenas vitórias mantêm a escalada.'),
(308, 'A clareza é condição de execução.'),
(309, 'O hábito certo sustenta o sucesso.'),
(310, 'A disciplina reduz a necessidade de motivação.'),
(311, 'O caminho é feito dia a dia.'),
(312, 'Defina o mínimo viável e execute.'),
(313, 'A consistência constrói confiança interna.'),
(314, 'A disciplina é a diferença entre intenção e resultado.'),
(315, 'Treine a paciência com ação diária.'),
(316, 'Seja fiel às pequenas promessas.'),
(317, 'A rotina é um contrato consigo mesmo.'),
(318, 'Progresso silencioso torna-se sucesso visível.'),
(319, 'A disciplina é investimento de longo prazo.'),
(320, 'Faça do processo seu principal ativo.'),
(321, 'A consistência cria autoridade natural.'),
(322, 'O hábito certo é a sua vantagem oculta.'),
(323, 'A clareza transforma intenção em plano.'),
(324, 'A disciplina é forjada em pequenos atos.'),
(325, 'Priorize hoje a vida que deseja ter.'),
(326, 'A ação contínua é antídoto contra o arrependimento.'),
(327, 'Faça do progresso uma obrigação gentil.'),
(328, 'Pequenas decisões feitas bem tornam-se poderosas.'),
(329, 'A rotina é habilidade externalizada.'),
(330, 'A consistência constrói um legado diário.'),
(331, 'Seja inflexível no processo, flexível no ajuste.'),
(332, 'A disciplina amplia sua margem de escolha.'),
(333, 'Cada dia é uma oportunidade de compor identidade.'),
(334, 'Pequenos passos, ritmo sustentável.'),
(335, 'A clareza precede a velocidade.'),
(336, 'A disciplina é o que te mantém em pé.'),
(337, 'A rotina é o mapa da sua reputação.'),
(338, 'Faça hoje o que evitará arrependimento.'),
(339, 'A consistência transforma intenção em hábito.'),
(340, 'A prática disciplinada vence talento adiado.'),
(341, 'Planeje bem, execute melhor.'),
(342, 'A rotina protege contra a emergência do impulso.'),
(343, 'A clareza economiza esforço.'),
(344, 'A disciplina é amor pelo resultado futuro.'),
(345, 'A consistência constrói confiança externa e interna.'),
(346, 'Trabalhe hoje para agradecer depois.'),
(347, 'Pequenas ações repetidas criam destino.'),
(348, 'A clareza permite escolhas firmes.'),
(349, 'Disciplina: escolha o que te edifica.'),
(350, 'A consistência é o hábito do vencedor.'),
(351, 'Use o tempo como aliado, não como inimigo.'),
(352, 'A disciplina transforma o potencial em realidade.'),
(353, 'O progresso é construção diária, não evento.'),
(354, 'A clareza é a lâmpada que guia a ação.'),
(355, 'Persistência é respeito pelo seu projeto.'),
(356, 'A rotina é o esqueleto das conquistas.'),
(357, 'Comprometa-se com o mínimo que funciona.'),
(358, 'A disciplina é hábito com propósito.'),
(359, 'Pequenos atos, influência duradoura.'),
(360, 'A consistência é a prova do seu compromisso.'),
(361, 'Faça do processo sua prioridade diária.'),
(362, 'A disciplina torna possível o extraordinário.'),
(363, 'Cada dia é chance de ser melhor.'),
(364, 'Persistir é transformar intenção em história.'),
(365, 'A soma dos dias faz sua vida.'),
(366, 'Hoje é um dia extra para fazer a diferença.');